---
# tasks file for elasticsearch
  - name: Установка elasticsearch
    become: true
    apt:
      deb: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearch/elasticsearch-7.17.1-amd64.deb"

  - name: Меняю host elasticsearch
    become: true
    ansible.builtin.lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: '^#network\.host: 192\.168\.0\.1$'
      line: 'network.host: "192.168.2.30"'

  - name: Меняю port elasticsearch
    become: true
    ansible.builtin.lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: '^#http\.port: 9200$'
      line: 'http.port: 9200'

  - name: Меняю discovery elasticsearch
    become: true
    ansible.builtin.lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: '^#discovery\.seed_hosts: \["host1", "host2"\]$'
      line: 'discovery.seed_hosts: ["192.168.2.30"]'
  
  - name: Меняю node name
    become: true
    ansible.builtin.lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: '^#node\.name: node-1$'
      line: 'node.name: node-1'

  - name: Меняю cluster
    become: true
    ansible.builtin.lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: '^#cluster\.initial_master_nodes: \["node-1", "node-2"\]$'
      line: 'cluster.initial_master_nodes: ["node-1"]'

  - name: daemon_reload
    systemd:
      daemon_reload: true

  - name: Перезапускаем elasticsearch и добавляем в автозагрузку
    service:
      name: elasticsearch
      state: restarted
      enabled: yes